### ISSUE TITLE
Add support for pydantic@2

### ISSUE THREAD

**Issue by DmytroLitvinov** [monim67/django-flatpickr#18]
**Describe the bug**
Currently, the project is based on pydantic@1, when there is pydantic@2

`poetry add django-flatpickr`
> Because django-flatpickr (2.0.1) depends on pydantic (<2)
 and no versions of django-flatpickr match >2.0.1,<3.0.0, django-flatpickr (>=2.0.1,<3.0.0) requires pydantic (<2).
So, because project depends on both pydantic (^2.1.1) and django-flatpickr (^2.0.1), version solving failed.

**Comment by dtcooper** [comment]
+1 on this one!

**Comment by monim67** [comment]
Release version 2.0.2 to support pydantic 2.
