### ISSUE TITLE
Can not integrate Date widget to Django User Sign Up form.

### ISSUE THREAD

**Issue by ghost** [monim67/django-flatpickr#3]
**Describe the problem**
Calendar widget is not displaying when I click on a date field,

**To Reproduce**
_forms.py_
```
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name', 'last_name', 'date_of_birth', 'email')
        widgets = {
            'date_of_birth': DatePickerInput(),
        }
```
_template_
```
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}
{% block extra_css %}
    {{ form.media.css }}
{% endblock %}
{% block extra_js %}
    {{ form.media.js }}
{% endblock %}
{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}
```

**Expected behavior**
The calendar should be displayed when I click on a date field.

**Console errors**
- No error on django console.
- No error on JavaScript console.

**Setup Information**
 - Python version 3.7
 - Django version  2.2

**Comment by monim67** [comment]
Does your base template contain `extra_css` and `extra_js` blocks?

**Comment by Sarcastic-Pharm** [comment]
Hi, I'm having a similar issue. I am wondering if it is a Django 2.2 issue? 

Same behavior as OP, same (lack of) console errors. Setup: 
Package                       Version
----------------------------- -------
asn1crypto                    0.24.0 
cffi                                 1.12.3 
cryptography                 2.6.1  
Django                           2.2.4  
django-debug-toolbar    2.0    
django-encrypted-model-fields 0.5.8  
django-field-history       0.7.0  
django-flatpickr             1.0.1  
pip                                19.0.3 
pycparser                     2.19   
pytz                              2019.1 
setuptools                    40.8.0 
six                                1.12.0 
sqlparse                       0.3.0 
Python version 3.7.3.

`
# base.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/h3.css' %}">
    {% block extra_css %}
    {% endblock %}
    {{ form.media }}
    <title>H3 Home Health Hire Program</title>
</head>
<body>
    <div class="page-header">
        <h2><a href="/" class="btn btn-dark top-menu">Settings</a></h2>
        {% if user.is_authenticated %}
            <h2><a href="{% url 'logout' %}?next={{ request.path }}" class="btn btn-dark top-menu">Logout</a></h2>
            <p class="top-menu">Logged in as : {{ user.username }}</p>
        {% else %}
            <h2><a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-dark top-menu">Login</a></h2>
        {% endif %}
    </div>
    <div class="page-header container">
        <h1><a href="/" class="page-title">H3 Home Health Hire</a></h1>
    </div>
    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>
    {% block extra_js %}
    {% endblock %}
</body>
</html>
`

`
#create_form.html

{% extends 'base.html' %}

{% block extra_css %}
    {{ form.media.css }}
{% endblock %}

{% block extra_js %}
    {{ form.media.js }}
{% endblock %}

{% block content %}
    <h2>
        New Hire for {{ customer.first_name }} {{ customer.last_name }}
        <a class="btn btn-secondary btn-right" onClick="window.history.back();return false;">Back</a>
    </h2>
    <form method="post" class="customer-form" autocomplete="off">{% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="customer" value="{{ customer.pk }}"/>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}
`

`
#forms.py

from django import forms

from flatpickr import DateTimePickerInput

from .models import HireTransaction


class HireForm(forms.ModelForm):

    class Meta:
        model = HireTransaction
        fields = (
            'customer',
            'staff_hiring',
            'asset',
            'date_out',
            'duration',
            'deposit',
            'delivery_charge',
            'notes'
        )
        widgets = {
            'customer': forms.HiddenInput,
            'date_out': DateTimePickerInput(),
        }
`

`
#settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'encrypted_model_fields',
    'field_history',
    'hire.apps.HireConfig',
    'customer.apps.CustomerConfig',
    'equipment.apps.EquipmentConfig',
    'purchase.apps.PurchaseConfig',
    'debug_toolbar',
    'flatpickr',
]
`
